server.port=18080

spring.datasource.url=jdbc:postgresql://localhost:5432/fx_raptor
spring.datasource.username=fx_user
spring.datasource.password=fx_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
